version: '2.2'

networks:
  vnclowpot_local:

services:

# vnclowpot service
  vnclowpot:
    build: .
    container_name: vnclowpot
    restart: always
    networks:
     - vnclowpot_local
    ports:
     - "5900:5900"
    image: "dtagdevsec/vnclowpot:1804"
    read_only: true
    volumes:
     - /data/vnclowpot/log:/var/log/vnclowpot
