# T-Pot (Standard)
# For docker-compose ...
version: '2.2'

networks:
  ciscoasa_local:

services:

# Ciscoasa service
  ciscoasa:
    build: .
    container_name: ciscoasa
    restart: always
    networks:
     - ciscoasa_local
    ports:
     - "5000:5000"
     - "8443:8443"
    image: "dtagdevsec/ciscoasa:1804"
    volumes:
     - /data/ciscoasa/log:/var/log/ciscoasa
