version: '2.2'

networks:
  mailoney_local:

services:

# Mailoney service
  mailoney:
    build: .
    container_name: mailoney
    restart: always
    stop_signal: SIGINT
    networks:
     - mailoney_local
    ports:
     - "25:2525"
    image: "dtagdevsec/mailoney:1804"
    read_only: true
    volumes:
     - /data/mailoney/log:/opt/mailoney/logs
