version: '2.2'

networks:
  glastopf_local:

services:

# Glastopf service
  glastopf:
    build: .
    container_name: glastopf
    environment:
      - PYTHON_EGG_CACHE=/tmp/glastopf
    tmpfs:
      - /tmp/glastopf:exec
    restart: always
    networks:
     - glastopf_local
    ports:
     - "80:80"
    image: "dtagdevsec/glastopf:1804"
    read_only: true
    volumes:
     - /data/glastopf/db:/opt/glastopf/db
     - /data/glastopf/log:/opt/glastopf/log
