version: '2.2'

services:

# Netdata service
  netdata:
    build: .
    container_name: netdata
    restart: always
    network_mode: "host"
    cap_add:
     - SYS_PTRACE
    security_opt:
     - apparmor=unconfined
    image: "dtagdevsec/netdata:1804"
    volumes:
     - /proc:/host/proc:ro
     - /sys:/host/sys:ro
     - /var/run/docker.sock:/var/run/docker.sock
    command: ["/usr/sbin/netdata","-D","-s","/host","-p","19999"]
