version: '2.3'

networks:
  tanner_local:

services:

# Tanner Redis Service
  tanner_redis:
    container_name: tanner_redis
    restart: always
    stop_signal: SIGKILL
    tty: true
    networks:
     - tanner_local
    image: "dtagdevsec/redis:1804"

# Tanner API Service
  tanner_api:
    build: .
    container_name: tanner_api
    restart: always
    stop_signal: SIGKILL
    tty: true
    networks:
     - tanner_local
    image: "dtagdevsec/tanner:1804"
    command: tannerapi 
    depends_on:
     - redis

# Tanner WEB Service
  tanner_web:
    build: .
    container_name: tanner_web
    restart: always
    stop_signal: SIGKILL
    tty: true
    networks:
     - tanner_local
    image: "dtagdevsec/tanner:1804"
    command: tannerweb
    depends_on:
     - redis

# Tanner Service
  tanner:
    build: .
    container_name: tanner
    restart: always
    stop_signal: SIGKILL
    tty: true
    networks:
     - tanner_local
    image: "dtagdevsec/tanner:1804"
    command: tanner
    depends_on:
     - tanner_api
     - tanner_web
