- name: Check host prerequisites
  hosts: localhost
  become: yes
  roles:
    - check

- name: Deploy instance
  hosts: localhost
  vars_files: my_os_cloud.yaml
  roles:
    - create_net
    - create_vm

- name: Install T-Pot on new instance
  hosts: tpot
  remote_user: linux
  become: yes
  gather_facts: no
  roles:
    - install
#    - custom_ews
#    - custom_hpfeeds
    - reboot
