- name: Check host prerequisites
  hosts: localhost
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - check

- name: Deploy instance
  hosts: localhost
  roles:
    - deploy

- name: Install T-Pot on new instance
  hosts: TPOT
  remote_user: linux
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - install
#    - custom_ews
#    - custom_hpfeeds
    - reboot
